"""Programa de 52 semanas para se tornar especialista em Data Matching / Entity Resolution.

Base: Christen, P. (2012). Data Matching: Concepts and Techniques for Record Linkage, Entity Resolution,
and Duplicate Detection. Springer. + literatura posterior (lista REFS: só referências verificadas).

Cada semana: 5 aulas de conceito (seg a sex), 1 laboratório (sáb) e 1 revisão ativa (dom).
`livro` = intervalos de páginas IMPRESSAS do livro (o PDF tem +16 páginas de deslocamento).
`refs`  = chaves de REFS que a aula pode citar.
"""

REFS = {
    "christen2012": "Christen, P. (2012). Data Matching. Springer.",
    "dunn1946": "Dunn, H. L. (1946). Record linkage. American Journal of Public Health, 36(12).",
    "newcombe1959": "Newcombe, H. B. et al. (1959). Automatic linkage of vital records. Science, 130.",
    "fs1969": "Fellegi, I. P. & Sunter, A. B. (1969). A theory for record linkage. JASA, 64(328).",
    "winkler1988": "Winkler, W. E. (1988). Using the EM algorithm for weight computation in the Fellegi-Sunter model of record linkage. Proc. ASA Survey Research Methods.",
    "jaro1989": "Jaro, M. A. (1989). Advances in record-linkage methodology as applied to matching the 1985 census of Tampa, Florida. JASA, 84(406).",
    "winkler1990": "Winkler, W. E. (1990). String comparator metrics and enhanced decision rules in the Fellegi-Sunter model of record linkage. Proc. ASA Survey Research Methods.",
    "herzog2007": "Herzog, T. N., Scheuren, F. J. & Winkler, W. E. (2007). Data Quality and Record Linkage Techniques. Springer.",
    "elmagarmid2007": "Elmagarmid, A. K., Ipeirotis, P. G. & Verykios, V. S. (2007). Duplicate record detection: a survey. IEEE TKDE, 19(1).",
    "getoor2012": "Getoor, L. & Machanavajjhala, A. (2012). Entity resolution: theory, practice & open challenges. PVLDB, 5(12).",
    "binette2022": "Binette, O. & Steorts, R. C. (2022). (Almost) all of entity resolution. Science Advances, 8(12).",
    "christophides2020": "Christophides, V. et al. (2020). An overview of end-to-end entity resolution for big data. ACM Computing Surveys, 53(6).",
    "dong2015": "Dong, X. L. & Srivastava, D. (2015). Big Data Integration. Morgan & Claypool.",
    "christen2006names": "Christen, P. (2006). A comparison of personal name matching: techniques and practical issues. IEEE ICDM Workshops.",
    "churches2002": "Churches, T., Christen, P., Lim, K. & Zhu, J. X. (2002). Preparation of name and address data for record linkage using hidden Markov models. BMC Medical Informatics and Decision Making, 2(9).",
    "philips2000": "Philips, L. (2000). The double metaphone search algorithm. C/C++ Users Journal, 18(6).",
    "christen2012index": "Christen, P. (2012). A survey of indexing techniques for scalable record linkage and deduplication. IEEE TKDE, 24(9).",
    "hernandez1995": "Hernández, M. A. & Stolfo, S. J. (1995). The merge/purge problem for large databases. ACM SIGMOD.",
    "mccallum2000": "McCallum, A., Nigam, K. & Ungar, L. H. (2000). Efficient clustering of high-dimensional data sets with application to reference matching. ACM KDD.",
    "michelson2006": "Michelson, M. & Knoblock, C. A. (2006). Learning blocking schemes for record linkage. AAAI.",
    "bilenko2006": "Bilenko, M., Kamath, B. & Mooney, R. J. (2006). Adaptive blocking: learning to scale up record linkage. IEEE ICDM.",
    "papadakis2020": "Papadakis, G., Skoutas, D., Thanos, E. & Palpanas, T. (2020). Blocking and filtering techniques for entity resolution: a survey. ACM Computing Surveys, 53(2).",
    "thirumuruganathan2021": "Thirumuruganathan, S. et al. (2021). Deep learning for blocking in entity matching: a design space exploration. PVLDB, 14(11).",
    "monge1996": "Monge, A. E. & Elkan, C. P. (1996). The field matching problem: algorithms and applications. ACM KDD.",
    "cohen2003": "Cohen, W. W., Ravikumar, P. & Fienberg, S. E. (2003). A comparison of string distance metrics for name-matching tasks. IIWeb (IJCAI Workshop).",
    "bilenko2003": "Bilenko, M. & Mooney, R. J. (2003). Adaptive duplicate detection using learnable string similarity measures. ACM KDD.",
    "linacre2022": "Linacre, R. et al. (2022). Splink: free software for probabilistic record linkage at scale. International Journal of Population Data Science, 7(3).",
    "enamorado2019": "Enamorado, T., Fifield, B. & Imai, K. (2019). Using a probabilistic model to assist merging of large-scale administrative records. American Political Science Review, 113(2).",
    "sarawagi2002": "Sarawagi, S. & Bhamidipaty, A. (2002). Interactive deduplication using active learning. ACM KDD.",
    "hassanzadeh2009": "Hassanzadeh, O., Chiang, F., Lee, H. C. & Miller, R. J. (2009). Framework for evaluating clustering algorithms in duplicate detection. PVLDB, 2(1).",
    "bhattacharya2007": "Bhattacharya, I. & Getoor, L. (2007). Collective entity resolution in relational data. ACM TKDD, 1(1).",
    "steorts2016": "Steorts, R. C., Hall, R. & Fienberg, S. E. (2016). A Bayesian approach to graphical record linkage and deduplication. JASA, 111(516).",
    "sadinle2017": "Sadinle, M. (2017). Bayesian estimation of bipartite matchings for record linkage. JASA, 112(518).",
    "hand2018": "Hand, D. & Christen, P. (2018). A note on using the F-measure for evaluating record linkage algorithms. Statistics and Computing, 28(3).",
    "harron2017": "Harron, K. et al. (2017). Challenges in administrative data linkage for research. Big Data & Society, 4(2).",
    "doidge2019": "Doidge, J. C. & Harron, K. L. (2019). Reflections on modern methods: linkage error bias. International Journal of Epidemiology, 48(6).",
    "gilbert2018": "Gilbert, R. et al. (2018). GUILD: GUidance for Information about Linking Data sets. Journal of Public Health, 40(1).",
    "christen2013geco": "Christen, P. & Vatsalan, D. (2013). Flexible and extensible generation and corruption of personal data. ACM CIKM.",
    "kopcke2010": "Köpcke, H., Thor, A. & Rahm, E. (2010). Evaluation of entity resolution approaches on real-world match problems. PVLDB, 3(1).",
    "schnell2009": "Schnell, R., Bachteler, T. & Reiher, J. (2009). Privacy-preserving record linkage using Bloom filters. BMC Medical Informatics and Decision Making, 9(41).",
    "vatsalan2013": "Vatsalan, D., Christen, P. & Verykios, V. S. (2013). A taxonomy of privacy-preserving record linkage techniques. Information Systems, 38(6).",
    "kuzu2011": "Kuzu, M., Kantarcioglu, M., Durham, E. & Malin, B. (2011). A constraint satisfaction cryptanalysis of Bloom filters in private record linkage. PETS.",
    "christen2020": "Christen, P., Ranbaduge, T. & Schnell, R. (2020). Linking Sensitive Data. Springer.",
    "christen2004geo": "Christen, P., Churches, T. & Willmore, A. (2004). A probabilistic geocoding system based on a national address file. AusDM.",
    "goldberg2008": "Goldberg, D. W. (2008). A Geocoding Best Practices Guide. NAACCR.",
    "christen2008rt": "Christen, P. & Gayler, R. (2008). Towards scalable real-time entity resolution using a similarity-aware inverted index approach. AusDM.",
    "gruenheid2014": "Gruenheid, A., Dong, X. L. & Srivastava, D. (2014). Incremental record linkage. PVLDB, 7(9).",
    "kolb2012": "Kolb, L., Thor, A. & Rahm, E. (2012). Dedoop: efficient deduplication with Hadoop. PVLDB, 5(12).",
    "konda2016": "Konda, P. et al. (2016). Magellan: toward building entity matching management systems. PVLDB, 9(12).",
    "ebraheem2018": "Ebraheem, M. et al. (2018). Distributed representations of tuples for entity resolution. PVLDB, 11(11).",
    "mudgal2018": "Mudgal, S. et al. (2018). Deep learning for entity matching: a design space exploration. ACM SIGMOD.",
    "li2020ditto": "Li, Y., Li, J., Suhara, Y., Doan, A. & Tan, W.-C. (2020). Deep entity matching with pre-trained language models. PVLDB, 14(1).",
    "narayan2022": "Narayan, A., Chami, I., Orr, L. & Ré, C. (2022). Can foundation models wrangle your data? PVLDB, 16(4).",
    "peeters2023": "Peeters, R., Steiner, A. & Bizer, C. (2023). Entity matching using large language models. arXiv:2310.11244 (EDBT 2025).",
    "ratner2017": "Ratner, A. et al. (2017). Snorkel: rapid training data creation with weak supervision. PVLDB, 11(3).",
    "ferreira2012": "Ferreira, A. A., Gonçalves, M. A. & Laender, A. H. F. (2012). A brief survey of automatic methods for author name disambiguation. ACM SIGMOD Record, 41(2).",
    "reimers2019": "Reimers, N. & Gurevych, I. (2019). Sentence-BERT: sentence embeddings using siamese BERT-networks. EMNLP.",
}

# (tema, páginas do livro impresso, refs, [5 aulas seg-sex], laboratório de sábado)
WEEKS = [
    # ---------------- Fase 1: fundamentos (cap. 1-2) ----------------
    ("O problema de data matching", [(3, 11)], ["christen2012", "elmagarmid2007", "binette2022"],
     ["Data matching, record linkage, entity resolution e deduplicação: definições precisas",
      "Por que não basta um JOIN: identificadores ausentes, errados e instáveis",
      "Complexidade quadrática: por que o número de pares explode e os matches não",
      "Falta de rótulos (ground truth) e o problema da avaliação",
      "Schema matching, data matching e data fusion: as três etapas da integração"],
     "Calcular o espaço de pares de duas bases e estimar a proporção de matches"),
    ("História e aplicações", [(9, 21)], ["dunn1946", "newcombe1959", "fs1969", "herzog2007"],
     ["De Dunn (1946) a Newcombe (1959): o nascimento do record linkage",
      "Fellegi-Sunter (1969): a primeira teoria formal",
      "Aplicações em censo, saúde e pesquisa populacional",
      "Segurança, fraude, crime e listas comerciais",
      "Bibliografia, e-commerce, ciências sociais e genealogia"],
     "Mapear 3 casos de uso reais de mercado e o tipo de linkage de cada um"),
    ("O processo de data matching de ponta a ponta", [(23, 35)], ["christen2012", "christophides2020"],
     ["Visão geral do processo e um pequeno exemplo completo",
      "Pré-processamento: o que entra e o que sai",
      "Indexação e geração de pares candidatos",
      "Comparação de pares e vetores de comparação",
      "Classificação, avaliação de qualidade e complexidade"],
     "Pipeline mínimo em Python (pandas + recordlinkage) no dataset FEBRL"),
    ("Formalização moderna de entity resolution", [(23, 35), (243, 250)], ["binette2022", "getoor2012", "christophides2020"],
     ["ER como clustering: registros, entidades e partições",
      "Tipos de tarefa: 1 para 1, deduplicação, multi-fonte, incremental",
      "Correspondências, transitividade e consistência das decisões",
      "Datasets de referência: FEBRL, DBLP-ACM, Abt-Buy, Amazon-Google",
      "Glossário do especialista: os termos que caem em entrevista"],
     "Construir uma partição de entidades a partir de pares e medir conflitos de transitividade"),
    # ---------------- Fase 2: pré-processamento (cap. 3) ----------------
    ("Qualidade de dados para matching", [(39, 51)], ["christen2012", "christen2006names"],
     ["Dimensões de qualidade que afetam o matching",
      "Nomes e dados pessoais: por que são difíceis",
      "Tipos e fontes de variação em nomes",
      "Erros tipográficos, fonéticos, de OCR e de transcrição",
      "Tarefas gerais de limpeza: valores ausentes, sentinelas e outliers"],
     "Perfilar uma base: preenchimento, frequências, sentinelas e formatos"),
    ("Pré-processamento para data matching", [(51, 58)], ["christen2012", "churches2002"],
     ["Remover caracteres e tokens indesejados",
      "Padronização e tokenização com tabelas de correspondência",
      "Segmentação em campos de saída",
      "Verificação contra bases de referência",
      "Nomes brasileiros: partículas, sobrenomes compostos e ordem"],
     "Escrever um padronizador de nomes e endereços brasileiros com testes"),
    ("Segmentação por regras e estatística", [(58, 66)], ["churches2002", "christen2012"],
     ["Segmentação baseada em regras: quando funciona e quando quebra",
      "Modelos estatísticos de segmentação: a intuição",
      "Hidden Markov Models para nomes e endereços",
      "Parsing de endereços hoje: CRF e libpostal",
      "Considerações práticas e questões de pesquisa"],
     "Comparar um parser de regras com o libpostal em 30 endereços"),
    # ---------------- Fase 3: indexação / blocking (cap. 4) ----------------
    ("Por que indexar e como definir blocking keys", [(69, 77)], ["christen2012", "christen2012index"],
     ["Por que indexar: o custo de comparar tudo",
      "Definindo blocking keys: critérios de escolha",
      "Codificação fonética: Soundex",
      "Phonex e Phonix",
      "NYSIIS"],
     "Medir tamanho dos blocos e pares perdidos com 3 blocking keys diferentes"),
    ("Codificações fonéticas e standard blocking", [(77, 81)], ["philips2000", "christen2012"],
     ["Oxford Name Compression Algorithm (ONCA)",
      "Double Metaphone",
      "Fuzzy Soundex e outras codificações",
      "Fonética para português: limitações e adaptações",
      "Standard blocking: funcionamento e armadilhas"],
     "Avaliar Soundex vs Double Metaphone em nomes brasileiros com erros"),
    ("Sorted neighbourhood, q-grams e suffix arrays", [(81, 89)], ["hernandez1995", "christen2012index"],
     ["Sorted neighbourhood: janela deslizante",
      "Variações do sorted neighbourhood (adaptativo, múltiplas passadas)",
      "Indexação baseada em q-grams",
      "Indexação por suffix array",
      "Comparando custo e recall dessas técnicas"],
     "Implementar sorted neighbourhood em Spark e medir pair completeness"),
    ("Canopy, mapping e comparação de técnicas", [(89, 97)], ["mccallum2000", "christen2012index"],
     ["Canopy clustering com limiares solto e apertado",
      "Indexação baseada em mapeamento (embedding em espaço métrico)",
      "Comparação sistemática das técnicas de indexação",
      "Outras técnicas: LSH e MinHash",
      "Como escolher a técnica pelo tamanho e pela qualidade dos dados"],
     "MinHash LSH para candidatos de nomes e comparação com standard blocking"),
    ("Blocking aprendido e blocking moderno", [(97, 100)], ["michelson2006", "bilenko2006", "papadakis2020", "thirumuruganathan2021"],
     ["Aprendendo blocking keys ótimos",
      "Token blocking e schema-agnostic blocking",
      "Meta-blocking: podando o grafo de blocos",
      "Blocking com embeddings e vizinhos aproximados",
      "Considerações práticas: skew, blocos gigantes e salting"],
     "Regras de blocking no Splink: contar pares e analisar cobertura"),
    # ---------------- Fase 4: comparação (cap. 5) ----------------
    ("Comparação exata e edit distance", [(101, 106)], ["christen2012", "cohen2003"],
     ["Por que comparar campo a campo",
      "Comparação exata, por truncamento e por codificação",
      "Levenshtein e Damerau-Levenshtein",
      "Smith-Waterman: alinhamento local",
      "Normalizando distâncias em similaridades"],
     "Implementar Levenshtein com programação dinâmica e comparar com RapidFuzz"),
    ("Q-grams e Jaro-Winkler", [(106, 111)], ["jaro1989", "winkler1990", "christen2006names"],
     ["Q-grams: Jaccard, Dice e overlap",
      "Q-grams posicionais e padding",
      "Jaro: transposições e caracteres em comum",
      "Winkler: o bônus de prefixo e por que funciona em nomes",
      "Escolhendo comparadores para nomes"],
     "Testar Jaro-Winkler vs q-gram Dice em pares de nomes rotulados"),
    ("Comparadores de tokens e textos", [(111, 118)], ["monge1996", "cohen2003", "christen2012"],
     ["Monge-Elkan para strings com vários tokens",
      "Extended Jaccard",
      "SoftTFIDF: combinando frequência e similaridade",
      "Longest common substring",
      "Bag distance, compressão, Editex e alinhamento silábico"],
     "Comparar Monge-Elkan e SoftTFIDF em nomes de empresas"),
    ("Números, datas e geografia", [(118, 125)], ["christen2012"],
     ["Exemplos comparativos de comparadores de strings",
      "Comparação numérica com tolerância",
      "Datas, idades e tempo: trocas dia/mês e janelas",
      "Distância geográfica: haversine e níveis",
      "Comparando dados complexos (listas, conjuntos, hierarquias)"],
     "Construir comparadores de data e geografia com níveis para um modelo de linkage"),
    ("Do campo ao registro", [(125, 127)], ["christen2012", "linacre2022", "reimers2019"],
     ["Vetores de comparação de registros",
      "Níveis de comparação (comparison levels) e como desenhá-los",
      "Valores ausentes na comparação",
      "Similaridade com embeddings de sentenças",
      "Considerações práticas: custo, bibliotecas e performance"],
     "Desenhar os níveis de comparação de nome, data e endereço no Splink"),
    # ---------------- Fase 5: classificação (cap. 6) ----------------
    ("Classificação por limiar e introdução probabilística", [(129, 137)], ["christen2012", "fs1969"],
     ["Visão geral da classificação de pares",
      "Classificação por limiar sobre similaridade somada",
      "Probabilidades m e u",
      "Pesos de concordância e discordância",
      "Match weight em log2 e interpretação"],
     "Calcular pesos m/u à mão para 4 campos e classificar 10 pares"),
    ("Fellegi-Sunter a fundo", [(133, 137)], ["fs1969", "herzog2007", "christen2012"],
     ["A razão de verossimilhança e a regra de decisão ótima",
      "Limiares superior e inferior e a zona de revisão",
      "Erros tipo I e tipo II no contexto de linkage",
      "Prior lambda: proporção de matches",
      "Probabilidade de match posterior"],
     "Implementar Fellegi-Sunter com pesos fixos em pandas"),
    ("EM e extensões do modelo", [(133, 137)], ["winkler1988", "jaro1989", "enamorado2019"],
     ["O algoritmo EM aplicado a record linkage",
      "EM passo a passo com números",
      "Independência condicional e quando ela falha",
      "Ajuste por frequência de termos (term frequency)",
      "Valores ausentes no modelo (abordagem do fastLink)"],
     "Rodar EM do zero em numpy e comparar com o Splink"),
    ("Splink na prática", [], ["linacre2022", "enamorado2019"],
     ["Arquitetura do Splink: settings, comparações e backends",
      "Estimando u por amostragem aleatória",
      "Estimando m com EM e regras de bloqueio de treino",
      "Lendo o waterfall chart e os pesos",
      "Escolhendo o limiar e gerando clusters"],
     "Modelo completo no Splink com DuckDB: treino, predição e clusters"),
    ("Custo, regras e aprendizado supervisionado", [(137, 147)], ["christen2012", "bilenko2003"],
     ["Classificação baseada em custo",
      "Classificação baseada em regras",
      "Aprendizado supervisionado: features e modelos",
      "Desbalanceamento extremo de classes",
      "Similaridades aprendidas"],
     "Treinar gradient boosting sobre vetores de comparação e comparar com FS"),
    ("Active learning e transitive closure", [(147, 154)], ["sarawagi2002", "hassanzadeh2009"],
     ["Active learning: escolhendo os pares mais informativos",
      "Dedupe e o ciclo humano no loop",
      "Transitive closure: o problema das cadeias",
      "Clustering para ER: componentes conexos, center e merge-center",
      "Correlation clustering e comparação de algoritmos"],
     "Comparar componentes conexos e center clustering no mesmo grafo de pares"),
    ("Coletivo, restrições e fusão", [(154, 162)], ["bhattacharya2007", "christen2012"],
     ["Classificação coletiva: usando relações como evidência",
      "Restrições de matching: atribuição 1 para 1",
      "Group linking (famílias, domicílios)",
      "Fusão de matches: golden record e regras de sobrevivência",
      "Considerações práticas e pesquisa em classificação"],
     "Atribuição ótima 1 para 1 com o algoritmo húngaro (scipy)"),
    ("Entity resolution bayesiano", [], ["steorts2016", "sadinle2017", "binette2022"],
     ["Por que modelar a incerteza do linkage",
      "Matchings bipartidos bayesianos",
      "ER gráfico com variáveis latentes de entidade",
      "Propagando incerteza para a análise final",
      "Quando o bayesiano vale a pena na prática"],
     "Simular a propagação da incerteza do linkage para uma estimativa simples"),
    # ---------------- Fase 6: avaliação (cap. 7) ----------------
    ("Medindo qualidade", [(163, 172)], ["christen2012"],
     ["Visão geral da avaliação",
      "Matriz de confusão para pares",
      "Precisão, recall e por que acurácia engana",
      "F-measure e curvas precisão-recall",
      "Escolha de limiar orientada pela métrica"],
     "Curva precisão-recall de um modelo e escolha de limiar"),
    ("Avaliação além do F1", [(172, 176)], ["hand2018", "hassanzadeh2009", "christen2012"],
     ["Críticas ao F-measure em linkage",
      "Métricas em nível de cluster (pairwise, B-cubed)",
      "Medindo complexidade: reduction ratio",
      "Pair completeness e pairs quality",
      "Clerical review: protocolo e amostragem"],
     "Calcular RR, PC e PQ de três estratégias de blocking"),
    ("Dados de teste e viés de linkage", [(176, 184)], ["christen2013geco", "harron2017", "doidge2019", "gilbert2018", "kopcke2010"],
     ["Dados públicos de teste e suas limitações",
      "Dados sintéticos: geração e corrupção controlada",
      "Viés de linkage: quem fica de fora",
      "Impacto de erros de linkage em estimativas",
      "Relatando qualidade de linkage (GUILD)"],
     "Gerar dados sintéticos com erros controlados e medir o impacto no modelo"),
    # ---------------- Fase 7: privacidade (cap. 8) ----------------
    ("Privacidade em data matching", [(187, 196)], ["christen2012", "vatsalan2013", "christen2020"],
     ["Desafios de privacidade e confidencialidade",
      "Acesso a identificadores e resultados sensíveis",
      "Cenários: duas partes, três partes e linkage unit",
      "Taxonomia das técnicas de PPRL",
      "LGPD e GDPR aplicadas a linkage"],
     "Desenhar o fluxo de um linkage com terceiro confiável e separação de dados"),
    ("Matching exato com privacidade", [(196, 199)], ["christen2020", "vatsalan2013"],
     ["Hashing de identificadores",
      "Salt, HMAC e chaves secretas",
      "Ataques de dicionário e de frequência",
      "Protocolos com terceiro confiável",
      "Limites do matching exato codificado"],
     "Mostrar um ataque de dicionário em hashes sem sal e corrigir com HMAC"),
    ("PPRL aproximado com Bloom filters", [(199, 203)], ["schnell2009", "kuzu2011", "christen2020"],
     ["Bloom filters: codificando q-grams",
      "Similaridade Dice entre Bloom filters",
      "Cryptographic long-term keys (CLK)",
      "Ataques a Bloom filters",
      "Hardening: balanceamento, XOR folding e salting"],
     "Codificar nomes em Bloom filters e comparar com Dice"),
    ("PPRL escalável e na prática", [(203, 207)], ["christen2020", "vatsalan2013"],
     ["Blocking com privacidade",
      "PPRL multi-parte",
      "Ferramentas: anonlink e clkhash",
      "Avaliação de qualidade em PPRL",
      "Considerações práticas e pesquisa"],
     "Linkage com clkhash e anonlink em dados sintéticos"),
    # ---------------- Fase 8: tópicos avançados (cap. 9) ----------------
    ("Geocodificação como matching", [(209, 211)], ["christen2004geo", "goldberg2008", "churches2002"],
     ["Geocodificação como problema de record linkage",
      "Bases de referência de endereços e o CNEFE",
      "Matching hierárquico de endereços",
      "Níveis de precisão e fallback",
      "Escore de confiança da geocodificação"],
     "Geocodificar endereços com matching hierárquico contra uma base de referência"),
    ("Geocodificação moderna e avaliação", [(209, 211)], ["goldberg2008"],
     ["libpostal, Nominatim e Pelias",
      "Interpolação e geocodificação por ponto",
      "Avaliando taxa de match e erro posicional",
      "Viés espacial da geocodificação",
      "Geocodificação e privacidade"],
     "Medir taxa de match e erro posicional de uma amostra auditada"),
    ("Dados complexos, tempo real e bases dinâmicas", [(211, 217)], ["christen2008rt", "gruenheid2014"],
     ["Matching de dados não estruturados e complexos",
      "Matching em tempo real (query-time ER)",
      "Índices invertidos com similaridade",
      "Linkage incremental",
      "Bases dinâmicas: entidades que mudam com o tempo"],
     "Serviço de busca de entidade em tempo real com índice invertido"),
    ("Matching paralelo e distribuído", [(217, 227)], ["kolb2012", "christen2012"],
     ["Paralelizando o processo de matching",
      "MapReduce e balanceamento de carga",
      "Skew de blocos e estratégias",
      "Spark: joins, particionamento e salting para ER",
      "Desafios e direções de pesquisa"],
     "Linkage em Spark com salting para blocos gigantes"),
    # ---------------- Fase 9: ER moderno ----------------
    ("Magellan e o ciclo de desenvolvimento de EM", [(229, 241)], ["konda2016", "kopcke2010"],
     ["Sistemas de data matching: checklist de avaliação",
      "Sistemas de pesquisa e open source (FEBRL e outros)",
      "Magellan: desenvolvimento x produção",
      "Benchmarks reais de entity matching",
      "Como escolher uma ferramenta de ER"],
     "Comparar recordlinkage, Splink e dedupe na mesma base"),
    ("Deep learning para entity matching", [], ["ebraheem2018", "mudgal2018"],
     ["DeepER: representações distribuídas de tuplas",
      "DeepMatcher: espaço de design",
      "Agregação de atributos: SIF, RNN e atenção",
      "Quando deep learning vence o clássico",
      "Custo de rótulos e de computação"],
     "Treinar um classificador com embeddings de atributos"),
    ("Transformers e Ditto", [], ["li2020ditto", "reimers2019"],
     ["Serialização de registros para modelos de linguagem",
      "Ditto: fine-tuning e injeção de conhecimento",
      "Data augmentation para matching",
      "Transfer learning entre domínios",
      "Limitações e custos em produção"],
     "Fine-tuning de um modelo pequeno para matching de pares"),
    ("LLMs para entity matching", [], ["narayan2022", "peeters2023"],
     ["Foundation models para tarefas de integração",
      "Prompting zero-shot e few-shot para matching",
      "Escolha de exemplos e formato de saída",
      "Custo, latência e cascatas com LLM",
      "Riscos: alucinação, viés e reprodutibilidade"],
     "Cascata: regra, depois modelo leve, depois LLM só nos casos ambíguos"),
    ("Embeddings e busca vetorial para ER", [], ["thirumuruganathan2021", "reimers2019"],
     ["Bi-encoders vs cross-encoders",
      "Índices de vizinhos aproximados (HNSW, FAISS)",
      "Blocking vetorial",
      "Aprendizado contrastivo para matching",
      "Avaliando recall de candidatos"],
     "Blocking vetorial com sentence-transformers e FAISS"),
    ("ER em grafos e identity graphs", [], ["bhattacharya2007", "ferreira2012"],
     ["ER em grafos de conhecimento e entity linking",
      "ER coletiva revisitada",
      "Algoritmos de grafos para clusters de entidades",
      "Identity graphs em marketing e risco",
      "Desambiguação de autores"],
     "Clusters de entidades com GraphFrames e análise de pontes fracas"),
    ("Arquitetura de uma plataforma de ER", [], ["christophides2020", "dong2015"],
     ["Arquitetura batch de ponta a ponta",
      "Identificadores persistentes de entidade",
      "Versionamento e reprocessamento",
      "Linkage incremental em produção",
      "Custos de nuvem e otimização"],
     "Desenhar a arquitetura de uma plataforma de ER (system design)"),
    ("Elasticsearch para matching", [], ["christen2008rt"],
     ["Elasticsearch como motor de candidatos",
      "Analyzers: n-gram, fonético e fuzzy",
      "Scoring BM25 e similaridade de matching",
      "Arquitetura de linkage com busca indexada",
      "Performance e tuning em escala"],
     "Linkage com consultas fuzzy no Elasticsearch e pós-classificação"),
    ("MDM e Customer 360", [(160, 162)], ["dong2015"],
     ["Master Data Management: conceitos",
      "Golden record e regras de sobrevivência",
      "Data stewardship e governança",
      "Customer 360 e CDPs",
      "Identity resolution em marketing"],
     "Regras de sobrevivência para gerar golden records"),
    ("Qualidade de ER em produção", [(183, 184)], ["enamorado2019", "doidge2019"],
     ["Monitorando a qualidade sem gold standard",
      "Estimando taxas de erro por amostragem",
      "Drift de dados e de modelo",
      "Testes automatizados de pipelines de ER",
      "Contratos de dados e observabilidade"],
     "Painel de monitoramento de qualidade de linkage"),
    # ---------------- Fase 11: domínios ----------------
    ("Saúde e pesquisa populacional", [(11, 13)], ["harron2017", "doidge2019", "enamorado2019"],
     ["Linkage de bases administrativas para pesquisa",
      "Linkage longitudinal e eventos repetidos",
      "Linkage mãe-filho e familiar",
      "Viés de linkage em populações vulneráveis",
      "Governança e ética"],
     "Desenho de um estudo com linkage e análise de sensibilidade"),
    ("Finanças, risco e crime", [(13, 15)], ["christen2006names"],
     ["KYC, AML e sanctions screening",
      "Name matching entre alfabetos e transliteração",
      "Redes de fraude e ER em grafos",
      "Falsos positivos e custo operacional",
      "Explicabilidade para auditoria"],
     "Screening de nomes contra uma lista de sanções com limiares"),
    ("Produtos, catálogos e bibliografia", [(17, 19)], ["ferreira2012", "kopcke2010", "peeters2023"],
     ["Product matching em e-commerce",
      "Atributos heterogêneos e texto livre",
      "Desambiguação de autores e citações",
      "Benchmarks de produtos",
      "Matching multimodal"],
     "Matching de produtos com TF-IDF e embeddings"),
    # ---------------- Fase 12: especialista ----------------
    ("Pesquisa em entity resolution", [(222, 227)], ["binette2022", "christophides2020", "getoor2012"],
     ["Como ler um paper de ER",
      "Principais venues e grupos de pesquisa",
      "Problemas em aberto",
      "Reprodutibilidade em ER",
      "Escolhendo um tema de pesquisa"],
     "Resumo crítico de um paper recente"),
    ("Entrevistas e system design de ER", [], ["christophides2020", "linacre2022"],
     ["System design: deduplicar 1 bilhão de registros",
      "Perguntas técnicas clássicas de entrevista",
      "Explicando trade-offs de precisão e recall para o negócio",
      "Casos de estudo para o portfólio",
      "Como apresentar seu trabalho em linkage"],
     "Simulação de entrevista de system design de ER"),
    ("Capstone e próximo ciclo", [], ["binette2022", "christen2012"],
     ["Projeto final: definição do problema",
      "Projeto final: pipeline e modelo",
      "Projeto final: avaliação e viés",
      "Projeto final: apresentação",
      "Plano de evolução para o próximo ano"],
     "Entregar o projeto final completo com relatório"),
]


def lessons() -> list[dict]:
    """365 aulas: 52 semanas x 7 dias + aula de encerramento."""
    out = []
    for w, (theme, pages, refs, days, lab) in enumerate(WEEKS, start=1):
        for d, title in enumerate(days, start=1):
            out.append({"semana": w, "tema": theme, "tipo": "conceito", "titulo": title,
                        "livro": pages, "refs": refs})
        out.append({"semana": w, "tema": theme, "tipo": "laboratorio", "titulo": f"Laboratório: {lab}",
                    "livro": pages, "refs": refs})
        out.append({"semana": w, "tema": theme, "tipo": "revisao",
                    "titulo": f"Revisão ativa da semana {w}: {theme}", "livro": pages, "refs": refs,
                    "conteudo_semana": days})
    out.append({"semana": 52, "tema": "Encerramento", "tipo": "revisao",
                "titulo": "Encerramento: o que um especialista em entity resolution domina",
                "livro": [], "refs": ["binette2022", "christen2012"],
                "conteudo_semana": [w[0] for w in WEEKS]})
    for i, l in enumerate(out, start=1):
        l["dia"] = i
    assert len(out) == 365, len(out)
    return out
