"""Aulas 1-30 (módulo 1) escritas à mão. Usado uma vez para semear lessons.json."""
import json
from pathlib import Path

L = [
 ("Record linkage é o processo de identificar registros que se referem à mesma entidade (pessoa, empresa, endereço) em uma ou mais bases, quando não existe um identificador único confiável. Ele existe porque dados são coletados por sistemas diferentes, com objetivos diferentes, e ninguém combinou antes uma chave comum. Sem linkage, cada base conta uma parte da história; com linkage, conseguimos acompanhar trajetórias: nascer, adoecer, receber um benefício, morrer. O desafio é que os mesmos atributos (nome, data de nascimento, nome da mãe) chegam com erros, abreviações e lacunas.",
  "'MARIA APARECIDA DOS SANTOS, 12/03/1985' no SINASC e 'MARIA AP. SANTOS, 12/03/1985' no CadÚnico: mesma pessoa?",
  "Quais perguntas de pesquisa do CIDACS seriam impossíveis sem linkage?"),
 ("Os termos se sobrepõem. 'Record linkage' vem da estatística e da saúde pública (Newcombe, Fellegi-Sunter). 'Entity resolution' vem da ciência da computação e bancos de dados, com foco em agrupar registros em entidades. 'Deduplicação' é o caso de uma base só. 'Entity matching' costuma designar a etapa de decidir se um par é match, muito usada na literatura de ML. 'Data matching', 'merge/purge' e 'object identification' também aparecem. Saber os sinônimos é essencial para buscar literatura e vagas.",
  "Buscar vagas só por 'record linkage' perde as que dizem 'entity resolution engineer'.",
  "Qual termo a sua área usa, e qual o mercado internacional usa?"),
 ("Linkage entre bases liga registros de fontes A e B (ex.: nascidos vivos × óbitos). Deduplicação encontra registros repetidos dentro da mesma base (ex.: a mesma pessoa cadastrada duas vezes no CadÚnico). A diferença muda o espaço de pares: entre bases são |A|×|B| pares; na deduplicação, n(n−1)/2. Também muda a restrição: em linkage entre bases, muitas vezes esperamos no máximo um par por registro (1-para-1), enquanto na deduplicação uma entidade pode ter vários registros.",
  "Base com 1 milhão de registros → ~5×10¹¹ pares possíveis na deduplicação.",
  "No seu trabalho, qual dos dois cenários é mais comum e qual é mais difícil?"),
 ("Se todo registro tivesse um CPF correto e sempre preenchido, linkage seria um join. Na prática, identificadores únicos faltam, estão errados (dígito trocado), são reaproveitados ou nem existem naquela base. Por isso usamos quase-identificadores: nome, sexo, data de nascimento, nome da mãe, município. Nenhum sozinho identifica alguém, mas a combinação sim. O problema de linkage é, no fundo, decidir quanta evidência basta quando a chave perfeita não existe.",
  "CPF preenchido em só 40% dos registros de uma base: o join por CPF perde 60% dos links.",
  "Mesmo quando existe um CPF, em que situações você não confiaria nele?"),
 ("No linkage determinístico, um par é match se satisfaz uma regra exata: por exemplo, nome padronizado igual E data de nascimento igual E município igual. É simples, rápido, explicável e costuma ter alta precisão. Seu ponto fraco é o recall: qualquer erro de digitação em um campo da regra faz o par ser perdido. Também é rígido diante de dados faltantes. É excelente como primeira etapa ou para gerar pares de treino de alta confiança.",
  "Regra: soundex(nome) = soundex(nome) AND dt_nasc = dt_nasc AND cod_mun = cod_mun.",
  "Que regra determinística você usaria como 'âncora' de alta precisão numa base do SUS?"),
 ("Para recuperar recall sem perder precisão, aplicamos várias regras em sequência (multi-pass). A primeira passada é a mais estrita; os pares encontrados saem do jogo. As passadas seguintes relaxam critérios (ex.: aceitam data com dia/mês trocado, ou nome com um caractere diferente) mas exigem outros campos. A ordem importa: regras estritas primeiro. Cada passada deve ser avaliada separadamente, pois a precisão tende a cair nas últimas.",
  "Passo 1: nome+nasc+mãe exatos. Passo 2: fonético(nome)+nasc+mun. Passo 3: nome+ano nasc+mãe.",
  "Como você mediria a precisão de cada passada isoladamente?"),
 ("O linkage probabilístico trata cada campo como evidência. Concordar em um sobrenome raro é evidência forte; concordar em sexo é fraca; discordar em data de nascimento é evidência contra. Somamos essas evidências (pesos) e obtemos um score. Em vez de 'tudo ou nada', o método tolera erros em alguns campos se os outros concordam fortemente. A formalização clássica é Fellegi-Sunter, que veremos a fundo no módulo 5.",
  "Nome igual + mãe igual + data com um dígito trocado → score alto mesmo sem concordância total.",
  "Por que concordar em 'SILVA' deveria valer menos do que concordar em 'WANDERLEY'?"),
 ("Comparar cada registro de A com cada registro de B gera |A|×|B| pares. Com 10 milhões de cada lado, são 10¹⁴ comparações — inviável. Porém quase todos esses pares são obviamente não-matches. Por isso o espaço de comparação precisa ser reduzido antes de comparar (blocking). Entender essa explosão quadrática é o que diferencia um script de linkage de um pipeline de produção.",
  "10⁷ × 10⁷ = 10¹⁴ pares; a 10⁷ comparações/s levaria ~4 meses.",
  "Qual é a razão entre matches reais e pares possíveis nas bases com que você trabalha?"),
 ("Em linkage probabilístico, cada par cai em uma de três classes: match (acima do limiar superior), não-match (abaixo do limiar inferior) e possível match (entre os dois). A zona intermediária é onde mora a incerteza e costuma ir para revisão manual ou regras adicionais. O tamanho dessa zona é uma decisão de custo: estreitá-la reduz revisão humana, mas aumenta erros.",
  "Score ≥ 12: match; score ≤ 4: não-match; 4–12: revisão.",
  "Quantos pares por dia uma equipe consegue revisar manualmente com qualidade?"),
 ("Falso positivo: ligar registros de pessoas diferentes (ex.: homônimos). Falso negativo: deixar de ligar registros da mesma pessoa. Os dois viesam análises de formas diferentes: falsos positivos misturam trajetórias (um óbito atribuído à pessoa errada), falsos negativos subestimam eventos (óbitos 'somem'). Não existe limiar que zere ambos; o objetivo do estudo define qual erro é mais caro.",
  "Estudo de mortalidade: falso negativo subestima a taxa de óbito da coorte.",
  "No seu projeto atual, qual erro é mais caro e por quê?"),
 ("O pipeline clássico tem etapas: (1) ingestão e perfilamento; (2) limpeza e padronização; (3) blocking/indexação para gerar pares candidatos; (4) comparação campo a campo, gerando vetores de similaridade; (5) classificação (regras, Fellegi-Sunter ou ML); (6) clustering para formar entidades; (7) avaliação e revisão manual. Cada etapa tem seus erros, e erros de etapas iniciais se propagam: um blocking ruim nunca é consertado pelo classificador.",
  "ingestão → padronização → blocking → comparação → classificação → clustering → avaliação",
  "Em qual etapa do seu pipeline você suspeita que mais links são perdidos?"),
 ("Identificadores diretos apontam para uma pessoa (CPF, CNS, NIS). Quase-identificadores são atributos que, combinados, identificam: nome, data de nascimento, sexo, nome da mãe, endereço. Diretos são poderosos mas nem sempre presentes ou confiáveis; quase-identificadores estão quase sempre presentes, mas com erros. Um bom linkage combina os dois tipos e sabe o quanto confiar em cada um.",
  "CNS igual mas data de nascimento muito diferente: possível CNS reaproveitado ou erro.",
  "Qual quase-identificador é mais confiável nas bases do SUS?"),
 ("Poder discriminante é a capacidade de uma variável separar matches de não-matches. Sexo tem baixo poder (50% dos não-matches concordam por acaso). Data de nascimento completa tem alto poder (chance de concordância por acaso ~1/25.000). O poder também depende da qualidade: um campo discriminante mas mal preenchido ajuda pouco. Em Fellegi-Sunter, isso aparece na razão m/u.",
  "u(sexo) ≈ 0,5; u(data nasc) ≈ 0,00004.",
  "Como estimar a probabilidade de coincidência por acaso de 'nome da mãe'?"),
 ("Linkage herda todos os problemas da coleta: campos vazios, erros de digitação, formatos inconsistentes, valores padrão ('IGNORADO', 01/01/1900) e mudanças de sistema ao longo dos anos. Antes de modelar, perfile os dados: taxa de preenchimento, distribuição de valores, valores mais frequentes. Muitos 'falsos matches' nascem de valores sentinela que concordam entre si.",
  "Duas pessoas com dt_nasc = 01/01/1900 concordam, mas é só o valor padrão do sistema.",
  "Quais valores sentinela você já encontrou nas bases com que trabalha?"),
 ("Cardinalidade define quantos links um registro pode ter. 1-para-1: cada nascido vivo tem no máximo um óbito. 1-para-N: uma pessoa tem várias internações. N-para-N: deduplicação com vários registros por pessoa em ambas as bases. Impor a restrição correta (ex.: atribuição ótima, ficando com o melhor par) melhora a precisão; impor a errada descarta links verdadeiros.",
  "Óbito ligado a dois nascidos vivos diferentes: violação de 1-para-1 → manter o de maior score.",
  "Qual restrição de cardinalidade vale para o linkage CadÚnico–SIH?"),
 ("Bases longitudinais registram eventos repetidos da mesma pessoa ao longo do tempo, e atributos mudam: endereço, sobrenome após casamento, até a grafia do nome. Linkage longitudinal precisa tolerar mudanças esperadas e usar a ordem temporal como evidência (um óbito não pode ocorrer antes do nascimento). Também precisa lidar com entidades que 'surgem' e 'desaparecem' das bases.",
  "Sobrenome de solteira na certidão de nascimento e de casada no CadÚnico.",
  "Que restrições temporais você poderia usar para eliminar falsos matches?"),
 ("Clerical review é a revisão manual de pares incertos por pessoas treinadas. Serve para decidir possíveis matches, criar dados rotulados e estimar a qualidade do linkage. Precisa de protocolo: quais campos mostrar, critérios de decisão, dupla revisão numa amostra e medição da concordância entre revisores (kappa). É caro, então deve ser direcionado para onde a informação é maior.",
  "Tela de revisão: par lado a lado, campos alinhados, diferenças destacadas, botões M / NM / ?",
  "Como garantir que dois revisores decidam de forma consistente?"),
 ("Ground truth são pares cuja condição de match é conhecida. Fontes: identificador único confiável num subconjunto (ex.: CPF validado), revisão manual, dados sintéticos com erros injetados, ou bases já ligadas por outro método validado. Cada fonte tem viés: pares com CPF podem ser 'mais fáceis' que a média. Um bom gold standard é amostrado de forma a representar os casos difíceis.",
  "Usar CPF presente em ambas as bases como rótulo, depois avaliar o modelo sem usar o CPF.",
  "Que viés existe em avaliar o linkage só nos registros que têm CPF?"),
 ("Em 1959, Howard Newcombe e colegas propuseram usar frequências de valores para ligar registros vitais no Canadá — a semente do linkage probabilístico. Em 1969, Ivan Fellegi e Alan Sunter formalizaram a teoria: dado um vetor de comparação, a regra ótima compara a razão de probabilidades m/u com limiares. Desde então, o modelo ganhou EM para estimar parâmetros (Winkler), métodos bayesianos e, mais recentemente, ML e deep learning.",
  "Newcombe (1959) → Fellegi-Sunter (1969) → Winkler/EM (anos 1980-90) → ML/DL (2010+).",
  "Por que um modelo de 1969 ainda é o padrão em saúde pública?"),
 ("No Brasil, o linkage de bases de saúde ganhou força com ferramentas como o RecLink (Camargo Jr. e Coeli), baseado em Fellegi-Sunter, muito usado em estudos epidemiológicos. Com o volume da Coorte de 100 Milhões, o CIDACS desenvolveu o CIDACS-RL, que usa indexação e busca em Elasticsearch para escalar o linkage a centenas de milhões de registros. Conhecer essa trajetória ajuda a contextualizar seu trabalho.",
  "RecLink: desktop, pareamento em blocos. CIDACS-RL: indexação + busca aproximada em escala.",
  "Que limitações do RecLink motivaram soluções baseadas em busca indexada?"),
 ("Em empresas, entity resolution aparece como Master Data Management (MDM): unificar clientes, fornecedores ou produtos espalhados em sistemas (CRM, ERP, e-commerce) em um 'golden record'. Além do matching, MDM envolve regras de sobrevivência (qual valor fica no registro mestre), governança e atualização contínua. Ferramentas: Informatica, Reltio, Tamr, Senzing. É um mercado com muitas vagas para quem domina matching.",
  "Três cadastros do mesmo cliente → um golden record com o e-mail mais recente e o CPF validado.",
  "Quais habilidades do seu trabalho transferem diretamente para MDM?"),
 ("Em grafos de conhecimento, ER decide se dois nós representam a mesma entidade do mundo real (ex.: 'IBM' e 'International Business Machines'). Aqui, além de atributos, as relações são evidência: dois autores com o mesmo nome e os mesmos coautores provavelmente são a mesma pessoa. Isso leva à ER coletiva, em que decisões de match se influenciam mutuamente.",
  "Autor 'J. Silva' com coautores {A, B} e 'João Silva' com {A, B, C}: forte evidência de match.",
  "Como relações familiares (mãe, irmãos) poderiam servir de evidência no seu linkage?"),
 ("Coortes administrativas dependem de linkage: sem ele, não há como seguir a mesma pessoa entre um benefício social e um desfecho de saúde. A validade dos resultados científicos depende diretamente da qualidade do linkage — e erros de linkage raramente são aleatórios. Por isso artigos sérios reportam como o linkage foi feito e sua qualidade estimada.",
  "Efeito do Bolsa Família sobre mortalidade infantil exige ligar CadÚnico, SINASC e SIM.",
  "Se o linkage falha mais para mães jovens, que efeito isso teria num estudo de mortalidade infantil?"),
 ("Mais comparações e comparadores mais sofisticados geralmente aumentam a qualidade, mas custam tempo e dinheiro. Blocking agressivo é barato, mas perde matches; comparar tudo é caro. LLMs são precisos, mas caros por par. Todo projeto real escolhe um ponto nesse trade-off. Uma boa estratégia é cascata: filtros baratos primeiro, métodos caros só nos casos ambíguos.",
  "Regra exata resolve 70% dos pares; modelo probabilístico, 25%; revisão humana, 5%.",
  "Onde no seu pipeline uma cascata economizaria mais?"),
 ("Um linkage precisa ser reprodutível: mesmas entradas e mesma configuração devem gerar os mesmos links. Documente versões das bases, regras de padronização, chaves de blocking, parâmetros do modelo, limiares, sementes aleatórias e métricas de qualidade. Guarde configurações em arquivos versionados (YAML/JSON) e não em código solto. Isso é essencial para auditoria, para publicação e para reprocessar quando uma base é atualizada.",
  "linkage_config_v3.yaml + hash das bases de entrada + relatório de qualidade gerado automaticamente.",
  "Se você tivesse que refazer um linkage de 2 anos atrás, conseguiria?"),
 ("Glossário: par candidato (par que sai do blocking); vetor de comparação (similaridades por campo); m-probability (P(concordância | match)); u-probability (P(concordância | não-match)); match weight (log2(m/u)); limiar (threshold); cluster (conjunto de registros da mesma entidade); golden record (registro consolidado); PPRL (linkage com preservação de privacidade); clerical review (revisão manual).",
  "match weight = log2(m/u) = log2(0,95/0,01) ≈ 6,6 bits",
  "Qual desses termos você usa com um nome diferente no dia a dia?"),
 ("Erros comuns: não padronizar antes de comparar; ignorar valores sentinela; blocking com uma chave só; avaliar apenas com pares fáceis; escolher limiar 'no olho'; não impor cardinalidade; esquecer o fecho transitivo (A=B, B=C, mas A≠C); não versionar configurações; tratar ausência de dados como discordância. Quase todos geram falsos positivos silenciosos.",
  "Nome da mãe vazio nos dois registros tratado como 'concorda' → falsos matches em massa.",
  "Qual desses erros você já cometeu ou já viu em produção?"),
 ("Estudo de caso: deduplicar 2 milhões de clientes. Passos: perfilar campos; padronizar nome, e-mail, telefone e endereço; blocking por (telefone), (e-mail) e (fonético do nome + CEP); comparar com Jaro-Winkler e igualdade; treinar Fellegi-Sunter com EM (ex.: Splink); definir limiar por revisão amostral; agrupar pares com componentes conexos; gerar golden record.",
  "Resultado típico: 2.000.000 registros → 1.740.000 clientes únicos.",
  "Que regra de sobrevivência você usaria para escolher o telefone do golden record?"),
 ("Estudo de caso: ligar nascidos vivos (SINASC) e óbitos infantis (SIM). Variáveis comuns: nome da mãe, data de nascimento da criança, sexo, município, peso ao nascer (quando presente). Muitos óbitos neonatais não têm nome da criança, então o nome da mãe é crucial. Impõe-se 1-para-1 e a restrição temporal (óbito após nascimento, idade compatível).",
  "Óbito sem nome da criança: linkage por nome da mãe + data de nascimento + município + sexo.",
  "Como o preenchimento do nome da criança no SIM afeta o recall desse linkage?"),
 ("Revisão do módulo 1: linkage liga registros sem chave única usando quase-identificadores; pode ser determinístico (regras) ou probabilístico (pesos de evidência); o espaço de pares explode quadraticamente e exige blocking; erros FP e FN têm custos diferentes; o pipeline vai da padronização à avaliação; qualidade e reprodutibilidade são tão importantes quanto o algoritmo.",
  "Resumo: dados sujos → padronizar → reduzir pares → comparar → decidir → agrupar → avaliar.",
  "Qual conceito deste módulo você explicaria para um colega novo primeiro?"),
]

out = Path(__file__).parent / "lessons.json"
import sys
sys.path.insert(0, str(Path(__file__).parent))
import syllabus
flat = syllabus.flat()
lessons = []
for i, (mod, title) in enumerate(flat, start=1):
    e = L[i - 1] if i <= len(L) else ("", "", "")
    lessons.append({"dia": i, "modulo": mod, "titulo": title,
                    "explicacao": e[0], "exemplo": e[1], "pergunta_reflexao": e[2]})
out.write_text(json.dumps(lessons, ensure_ascii=False, indent=1), "utf-8")
print(sum(1 for l in lessons if l["explicacao"]), "aulas completas de", len(lessons))
