"""Cronograma de 365 aulas (12 módulos progressivos). Fonte para scripts/build_lessons.py."""

MODULES = [
    ("1. Fundamentos", [
        "O que é record linkage e por que ele existe",
        "Entity resolution, record linkage e deduplicação: diferenças de nomenclatura",
        "Linkage entre bases vs deduplicação dentro de uma base",
        "O problema da ausência de chave única",
        "Linkage determinístico: regras exatas",
        "Linkage determinístico em etapas (multi-pass)",
        "Linkage probabilístico: a intuição",
        "Pares, espaço de comparação e explosão quadrática",
        "Match, não-match e possível match",
        "Tipos de erro: falso positivo e falso negativo",
        "O pipeline clássico de linkage de ponta a ponta",
        "Variáveis identificadoras: diretas e quase-identificadores",
        "Poder discriminante de uma variável",
        "Qualidade de dados e seu impacto no linkage",
        "Linkage 1-para-1, 1-para-N e N-para-N",
        "Linkage de bases longitudinais e eventos repetidos",
        "Clerical review: o papel do revisor humano",
        "Ground truth: como obter pares verdadeiros",
        "Breve história: de Newcombe (1959) a Fellegi-Sunter (1969)",
        "Ferramentas de linkage: do RecLink aos motores de busca indexada",
        "Entity resolution em empresas: MDM e golden record",
        "Entity resolution em grafos de conhecimento",
        "Linkage e ciência: por que coortes dependem dele",
        "Custo computacional vs qualidade: o trade-off central",
        "Documentando um linkage: reprodutibilidade",
        "Glossário essencial de linkage",
        "Erros comuns de quem começa em linkage",
        "Estudo de caso: deduplicar um cadastro de clientes",
        "Estudo de caso: ligar nascimentos e óbitos",
        "Revisão do módulo 1",
    ]),
    ("2. Pré-processamento e padronização", [
        "Por que padronizar antes de comparar",
        "Caixa, acentos e Unicode (NFKD)",
        "Remoção de pontuação e espaços",
        "Stopwords em nomes: DE, DA, DOS, E",
        "Separação de nome, nome do meio e sobrenome",
        "Apelidos e nomes abreviados",
        "Nomes compostos e ordem invertida",
        "Nomes de mãe como variável de linkage",
        "Padronização de datas e formatos",
        "Datas faltantes, parciais e inválidas",
        "Sexo, raça/cor e variáveis categóricas",
        "CPF, CNS e NIS: validação de dígitos verificadores",
        "Tratamento de valores sentinela (99999, 'IGNORADO')",
        "Fonética: por que o som importa",
        "Soundex: algoritmo e limitações",
        "Metaphone e Double Metaphone",
        "NYSIIS e Caverphone",
        "BuscaBR: fonética para o português",
        "Fonética em português: armadilhas (CH, X, LH, NH)",
        "Padronização de endereços: visão geral",
        "Tipos de logradouro: R., RUA, AV., AVENIDA",
        "Números, complementos e 'S/N'",
        "Bairros, distritos e nomes informais",
        "CEP como variável de linkage",
        "Municípios: códigos IBGE vs nomes",
        "Tokenização de strings",
        "Normalização de nomes de empresas (LTDA, S.A., ME)",
        "Detecção de dados sintéticos e lixo",
        "Perfilamento de dados (data profiling) antes do linkage",
        "Pipeline de padronização reprodutível em Python",
        "Pré-processamento em escala com Spark",
        "Revisão do módulo 2",
    ]),
    ("3. Comparação de strings", [
        "Comparação exata vs aproximada",
        "Distância de Hamming",
        "Distância de Levenshtein",
        "Damerau-Levenshtein e transposições",
        "Similaridade de Jaro",
        "Jaro-Winkler e o bônus de prefixo",
        "Por que Jaro-Winkler funciona bem para nomes",
        "Longest Common Subsequence",
        "Q-grams e bigramas",
        "Coeficiente de Jaccard",
        "Dice e Sørensen",
        "Similaridade de cosseno com q-grams",
        "TF-IDF para strings",
        "Monge-Elkan para strings multi-token",
        "Soft TF-IDF",
        "Comparação de nomes com tokens fora de ordem",
        "Comparação numérica: idade, datas e tolerâncias",
        "Comparação de datas com trocas de dia/mês",
        "Comparação geográfica: distância haversine",
        "Níveis de comparação (comparison levels)",
        "Escolhendo limiares de similaridade",
        "RapidFuzz na prática",
        "Performance: vetorização de comparações",
        "Comparação com embeddings de caracteres",
        "Comparação de strings no Elasticsearch",
        "Fuzzy queries e n-gram analyzers no Elasticsearch",
        "Comparadores específicos por campo",
        "Combinando comparadores em um vetor de comparação",
        "Missing values na comparação",
        "Avaliando comparadores com pares rotulados",
        "Armadilhas: nomes comuns e similaridade alta enganosa",
        "Revisão do módulo 3",
    ]),
    ("4. Blocking e indexação", [
        "Por que blocking é obrigatório",
        "Standard blocking",
        "Escolha de chaves de blocking",
        "Blocking com códigos fonéticos",
        "Múltiplas passadas de blocking (união de regras)",
        "Sorted neighborhood",
        "Sorted neighborhood adaptativo",
        "Q-gram indexing",
        "Suffix array blocking",
        "Canopy clustering",
        "Locality Sensitive Hashing (LSH): intuição",
        "MinHash para Jaccard",
        "SimHash e LSH para cosseno",
        "Blocking com embeddings e vizinhos aproximados (ANN)",
        "Meta-blocking",
        "Métricas de blocking: reduction ratio",
        "Pair completeness e pairs quality",
        "Blocos gigantes e skew",
        "Blocking em Spark: joins e particionamento",
        "Salting para blocos desbalanceados",
        "Blocking em Splink: blocking rules",
        "Blocking com Elasticsearch como índice de candidatos",
        "Blocking aprendido (learned blocking)",
        "Blocking hierárquico para endereços",
        "Blocking em linkage incremental",
        "Contando pares antes de rodar",
        "Blocking e viés: quem fica de fora",
        "Estudo de caso: blocking em bilhões de registros",
        "Otimização de custo em cluster",
        "Blocking para PPRL",
        "Blocking com LLMs e embeddings semânticos",
        "Revisão do módulo 4",
    ]),
    ("5. Modelo Fellegi-Sunter e EM", [
        "Fellegi-Sunter: formulação",
        "Probabilidade m",
        "Probabilidade u",
        "Pesos de concordância e discordância",
        "Match weight e log-verossimilhança",
        "Somando pesos: a hipótese de independência condicional",
        "Limiares superior e inferior",
        "Probabilidade de match posterior",
        "Prior: proporção de matches (lambda)",
        "Estimando u por amostragem aleatória",
        "Estimando m com pares rotulados",
        "Algoritmo EM: intuição",
        "EM passo a passo",
        "Convergência e mínimos locais no EM",
        "Pesos dependentes de frequência (term frequency)",
        "Nomes raros vs nomes comuns",
        "Níveis parciais de concordância",
        "Missing values no Fellegi-Sunter",
        "Violação da independência condicional",
        "Fellegi-Sunter em Splink",
        "Lendo um waterfall chart de pesos",
        "Treinando m e u separadamente no Splink",
        "Deterministic rules para estimar lambda",
        "Fellegi-Sunter vs regressão logística",
        "Bayesian record linkage",
        "Modelos de mistura com mais de 2 classes",
        "Calibração de probabilidades de match",
        "Estudo de caso: modelo FS para dados do SUS",
        "Diagnóstico de um modelo mal treinado",
        "Revisão do módulo 5",
    ]),
    ("6. Avaliação", [
        "Por que avaliar é difícil em linkage",
        "Matriz de confusão para pares",
        "Precisão",
        "Recall (sensibilidade)",
        "F1 e suas críticas em linkage",
        "Curva precisão-recall",
        "Escolhendo o limiar ótimo",
        "Avaliação em nível de par vs nível de cluster",
        "Métricas de clustering: B-cubed, pairwise, CEAF",
        "Amostragem para revisão manual",
        "Amostragem estratificada por score",
        "Clerical review: protocolos e concordância entre revisores",
        "Gold standard sintético",
        "Geradores de dados sintéticos (FEBRL, GeCo)",
        "Estimando precisão sem gold standard",
        "Viés de linkage: o que é",
        "Quem não é linkado: grupos sub-representados",
        "Impacto de erros de linkage em estimativas epidemiológicas",
        "Correção de viés de linkage (pesos, imputação)",
        "Sensibilidade: rodar com vários limiares",
        "Relatando qualidade de linkage (GUILD)",
        "Monitoramento contínuo de qualidade em produção",
        "Testes automatizados para pipelines de linkage",
        "Painéis de qualidade de linkage",
        "Estudo de caso: avaliando linkage nascimento-óbito",
        "Erros sistemáticos: gêmeos, homônimos e famílias",
        "Avaliando geocodificação: taxa de match e acurácia posicional",
        "Revisão do módulo 6",
    ]),
    ("7. ML e Deep Learning para ER", [
        "Linkage como classificação supervisionada",
        "Features a partir de vetores de comparação",
        "Árvores, random forest e gradient boosting para matching",
        "Desbalanceamento extremo de classes",
        "Active learning para rotular pares",
        "Dedupe (biblioteca) e active learning",
        "Magellan / py_entitymatching",
        "DeepMatcher",
        "Transformers para matching de registros",
        "Ditto: entity matching com modelos de linguagem",
        "Serialização de registros para modelos de linguagem",
        "Embeddings de sentenças para ER",
        "Sentence-BERT e bi-encoders",
        "Cross-encoders vs bi-encoders",
        "Busca vetorial para candidatos",
        "Contrastive learning para matching",
        "Transfer learning entre domínios",
        "Few-shot e zero-shot matching",
        "LLMs como juízes de pares",
        "Prompting para entity matching",
        "Custo e latência de LLMs em matching",
        "Cascatas: regra → modelo leve → LLM",
        "Explicabilidade de decisões de match",
        "Fairness em modelos de matching",
        "Benchmarks: Abt-Buy, Amazon-Google, DBLP-ACM",
        "Limitações dos benchmarks acadêmicos",
        "Matching multimodal (texto + imagem)",
        "Matching de produtos e catálogos",
        "Matching de empresas e organizações",
        "Matching de publicações científicas e autores",
        "Author name disambiguation",
        "Entity linking com bases de conhecimento (Wikidata)",
        "Estado da arte recente em ER com LLMs",
        "Revisão do módulo 7",
    ]),
    ("8. Geocodificação como linkage", [
        "Geocodificação: definição e tipos",
        "Geocodificação como problema de record linkage",
        "Endereço como registro estruturado",
        "Address parsing: regras vs modelos",
        "libpostal: parsing e normalização",
        "Parsing de endereços brasileiros",
        "Gazetteers e bases de referência",
        "CNEFE: o cadastro de endereços do IBGE",
        "Faces de logradouro e setores censitários",
        "OpenStreetMap como referência",
        "Bases de CEP e suas limitações",
        "Matching hierárquico: UF → município → bairro → logradouro",
        "Matching de nomes de logradouro",
        "Interpolação de número ao longo do segmento",
        "Geocodificação por ponto de endereço vs segmento",
        "Fallback: centroide de CEP, setor ou município",
        "Nível de precisão (match level) do resultado",
        "Score de confiança da geocodificação",
        "Geocodificação reversa",
        "Geocoders: Nominatim, Pelias, Photon",
        "Geocoders comerciais: Google, HERE, Esri",
        "Geocodificação em lote e limites de API",
        "Construindo um geocodificador próprio com Elasticsearch",
        "Blocking espacial e índices geográficos",
        "Endereços rurais e informais",
        "Favelas e comunidades: desafios de endereçamento",
        "Mudanças de nome de logradouros ao longo do tempo",
        "Geocodificação e privacidade (reidentificação)",
        "Avaliando geocodificação com amostra auditada",
        "Viés geográfico: quem falha na geocodificação",
        "Geocodificação em saúde pública",
        "What3words, Plus Codes e alternativas",
        "Estudo de caso: geocodificar endereços do SIM/SINASC",
        "Revisão do módulo 8",
    ]),
    ("9. Escalabilidade", [
        "Quando o linkage deixa de caber em uma máquina",
        "Spark: modelo de execução para linkage",
        "Joins em Spark: broadcast vs shuffle",
        "Particionamento e skew em Spark",
        "Splink: arquitetura e backends (DuckDB, Spark)",
        "Splink na prática: do treino à predição",
        "Zingg: ER escalável com active learning",
        "Senzing: ER em tempo real",
        "Elasticsearch como motor de candidatos em escala",
        "DuckDB para linkage de médio porte",
        "Linkage incremental e streaming",
        "Clustering de pares em entidades",
        "Fecho transitivo e componentes conexos",
        "Connected components em grafos gigantes (GraphFrames)",
        "Problema do encadeamento: clusters gigantes",
        "Correlation clustering e corte de arestas fracas",
        "Clustering hierárquico para ER",
        "Identificadores persistentes de entidade",
        "Versionamento de resultados de linkage",
        "Orquestração: Airflow e pipelines agendados",
        "Custo de nuvem e otimização",
        "Formatos colunares: Parquet e Delta",
        "Observabilidade do pipeline",
        "Testes de regressão em linkage",
        "Estudo de caso: pipeline com bilhões de pares",
        "Estratégias de reprocessamento",
        "Paralelizando comparação de strings",
        "GPU para similaridade em massa",
        "Arquitetura de referência de uma plataforma de linkage",
        "Revisão do módulo 9",
    ]),
    ("10. Privacidade", [
        "Por que privacidade importa em linkage",
        "LGPD e dados de saúde",
        "Anonimização vs pseudonimização",
        "Modelo de terceiro confiável (trusted third party)",
        "Separação de identificadores e dados de conteúdo",
        "Privacy-preserving record linkage (PPRL): visão geral",
        "Hashing de identificadores e suas fraquezas",
        "Bloom filters para PPRL",
        "Comparando Bloom filters: Dice",
        "Ataques a Bloom filters (frequency attacks)",
        "Hardening de Bloom filters",
        "Cryptographic long-term keys (CLK)",
        "Anonlink e ferramentas de PPRL",
        "Secure multiparty computation em linkage",
        "Privacidade diferencial e linkage",
        "Blocking com preservação de privacidade",
        "Avaliação de qualidade em PPRL",
        "Governança e comitês de ética",
        "Salas seguras e ambientes controlados",
        "Risco de reidentificação após linkage",
        "Dados geográficos e reidentificação",
        "Termos de uso e acordos de compartilhamento",
        "Auditoria e logs de acesso",
        "Estudo de caso: PPRL em saúde pública",
        "Revisão do módulo 10",
    ]),
    ("11. Casos reais em saúde pública", [
        "Por que linkage transformou a epidemiologia",
        "Grandes coortes administrativas: como são construídas",
        "Infraestruturas de dados para linkage em larga escala",
        "CadÚnico como base de linkage",
        "Bolsa Família e desfechos de saúde",
        "SIM: Sistema de Informação sobre Mortalidade",
        "SINASC: Nascidos Vivos",
        "SINAN: agravos de notificação",
        "SIH: internações hospitalares",
        "Linkage CadÚnico–SIM",
        "Linkage SINASC–SIM: mortalidade infantil",
        "Linkage para tuberculose e hanseníase",
        "Coortes de nascimentos e Zika",
        "Linkage para COVID-19: vacinação e desfechos",
        "Linkage longitudinal: trajetórias de vida",
        "Mães e filhos: linkage familiar",
        "Variáveis disponíveis nas bases do SUS",
        "Qualidade de preenchimento nas bases do SUS",
        "Viés de linkage em populações vulneráveis",
        "Publicando resultados baseados em linkage",
        "Experiências internacionais: Escócia, Austrália, Canadá",
        "Population Data BC e SAIL Databank",
        "Linkage e avaliação de políticas públicas",
        "Linkage com dados de censo",
        "Lições aprendidas em produção",
        "Revisão do módulo 11",
    ]),
    ("12. Revisão e tópicos avançados", [
        "Revisão: do problema ao pipeline",
        "Revisão: padronização e fonética",
        "Revisão: comparadores",
        "Revisão: blocking",
        "Revisão: Fellegi-Sunter",
        "Revisão: avaliação e viés",
        "Revisão: ML e LLMs",
        "Revisão: geocodificação",
        "Revisão: escala e grafos",
        "Revisão: privacidade",
        "Linkage temporal e registros que mudam",
        "Linkage multi-fonte (mais de duas bases)",
        "Resolução de entidades colaborativa (collective ER)",
        "ER em grafos heterogêneos",
        "Record linkage com dados textuais livres",
        "Linkage de dados históricos (censos antigos)",
        "Incerteza de linkage propagada para análises",
        "Múltipla imputação de links",
        "Modelos bayesianos de ER em larga escala",
        "Agentes de IA para curadoria de linkage",
        "Tendências de pesquisa em ER",
        "Como ler um paper de record linkage",
        "Como escrever um paper de record linkage",
        "Montando seu portfólio em linkage",
        "Carreira: onde trabalham especialistas em ER",
        "Desenhe um pipeline de linkage do zero (exercício)",
        "Desenhe um geocodificador do zero (exercício)",
        "Desenhe um sistema de PPRL (exercício)",
        "Estudo livre: escolha um tema para aprofundar",
        "Mestrado e mercado: conectando pesquisa e prática",
        "Grandes perguntas em aberto em record linkage",
        "Encerramento do ano e plano para o próximo ciclo",
    ]),
]


def flat() -> list[tuple[str, str]]:
    """Lista de (módulo, título), completada até 365 com aulas práticas por módulo."""
    items = [(m, t) for m, ts in MODULES for t in ts]
    i = 0
    while len(items) < 365:  # completa com exercícios práticos dos módulos, em ordem
        m, ts = MODULES[i % len(MODULES)]
        pos = max(k for k, (mm, _) in enumerate(items) if mm == m) + 1
        items.insert(pos, (m, f"Prática guiada: {ts[(i // len(MODULES)) % (len(ts) - 1)]}"))
        i += 1
    return items[:365]
